### ISSUE TITLE
Machine Upgrades not Dropped when Machine is Wrenched

### ISSUE THREAD

**Issue by Drathonix** [TechReborn/TechReborn-Legacy-Issues#3] opened 2019-12-30 19:04 UTC
RebornCore: 3.16.4.478
TechReborn: 2.24.3.1043

When a machine has upgrades in it, they are not dropped when the machine is picked up using a wrench, deleting the upgrades entirely.

**Comment by drcrazy** [comment] 2020-01-17 11:58
Can't reproduce. Might be already fixed in dev.

![image](https://user-images.githubusercontent.com/1382352/72610932-cb99e100-3939-11ea-85cc-978f6594605b.png)

**Closed as completed by drcrazy** 2020-01-17 11:58 UTC
Labels: bug
